lesson5/pusher_lite_demo/config/routes.rb
Rails.application.routes.draw do
  resources :events, only: [:create]

  root 'home#index'

end

lesson5/pusher_lite_demo/app/models/pusher_event.rb
require "net/http"
require "uri"
class PusherEvent
  include ActiveModel::Model

  attr_accessor :name, :message, :broadcast
  validates :name, :message, presence: true

  def jwt(token)
    JWT.encode(jwt_claims(token), Rails.application.secrets.pusher_secret, 'HS256')
  end

  def jwt_claims(token)
    {
      iss: "ExPusherLite",
    }
  end

  def save
    topic = Rails.application.secrets.pusher_channel

    encoded_token = Base64.urlsafe_encode64(SecureRandom.random_bytes(32))

    token = jwt(encoded_token)

    uri = PusherLite.uri
    Net::HTTP.start(uri.host, uri.port) do |http|
      request = Net::HTTP::Post.new uri
      request.add_field('Content-Type', 'application/json')
      ###
      request.add_field("Authorization", "Bearer #{token}")
      ###
      request.body = {
        "topic" => topic,
        "event" => "msg",
        "scope" => "public",
        "payload" => {"name" => name, "message" => message}.to_json}.to_json
      http.request request
    end
  end

end

lesson5/pusher_lite_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lesson5/pusher_lite_demo/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    SendEventsJob.perform_later(event_params)
  end

  def event_params
    params.require(:pusher_event).permit(:name, :message, :broadcast)
  end
end

lesson5/pusher_lite_demo/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @event = PusherEvent.new
  end
end

lesson5/pusher_lite_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

lesson5/pusher_lite_demo/app/helpers/events_helper.rb
module EventsHelper
end

lesson5/pusher_lite_demo/app/helpers/guardian_helper.rb
module GuardianHelper
  ISSUER = "pl-web-#{Rails.env}"
  DIGEST = OpenSSL::Digest.new('sha256')

  def guardian_token_tags
    token = Base64.urlsafe_encode64(SecureRandom.random_bytes(32))
    [
      "<meta content=\"#{jwt(token)}\" name=\"guardian-csrf\" />",
      "<meta content=\"#{jwt(token)}\" name=\"guardian-token\" />",
    ].shuffle.join.html_safe
  end

  private

  def jwt(token)
    JWT.encode(jwt_claims(token), Rails.application.secrets.pusher_secret, 'HS256')
  end

  def jwt_claims(token)
    {
      # aud: :csrf,
      # aud: :token,
      # sub: jwt_sub,
      # iss: ISSUER,
      iss: "ExPusherLite",
      # iat: Time.now.utc.to_i,
      # exp: (Time.now + 30.days).utc.to_i,
      # s_csrf: guardian_signed_token(token),
      # listen: jwt_listens,
      # publish: jwt_publish,
    }
  end

  def jwt_sub
    return {} unless current_human.present?
    {
      id: current_human.id,
      name: current_human.full_name,
      email: current_human.email,
      crews: current_human.crews.map(&:identifier),
    }
  end

  def jwt_listens
    listens = ['deploys:web', 'public:*']
    listens.push('private:*') if current_human.try(:in_crew?, :admins)
    listens
  end

  def jwt_publish
    publish = ['public:*']
    publish.push('private:*') if current_human.try(:in_crew?, :admins)
    publish
  end

  def guardian_signed_token(token)
    key = Rails.application.secrets.pusher_key
    signed_token = OpenSSL::HMAC.digest(DIGEST, key, token)
    Base64.urlsafe_encode64(signed_token).gsub(/={1,}$/, '')
  end
end

lesson5/pusher_lite_demo/app/helpers/home_helper.rb
module HomeHelper
end

lesson5/pusher_lite_demo/app/views/events/create.js.erb
$(".message-form #pusher_event_message").val("");
$(".message-form #pusher_event_message").focus();

lesson5/pusher_lite_demo/app/views/home/index.html.erb
<%= form_for @event, url: events_path, remote: true, html: {class: "pure-form pure-form-stacked"} do |f| %>
  <fieldset>
    <legend>Send your message remotely</legend>
    <%= f.text_field :name, placeholder: "Name" %>
    <%= f.text_field :message, placeholder: "Message" %>
    <%= f.check_box :broadcast %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <%= f.submit "Send message", class: "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

lesson5/pusher_lite_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pusher Lite Demo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="pusher_host" content="<%= Rails.application.secrets.pusher_url %>">
  <meta name="pusher_app_id" content="<%= Rails.application.secrets.pusher_app_id %>">
  <meta name="pusher_channel" content="<%= Rails.application.secrets.pusher_channel %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body data-route="application/pages/<%= controller.controller_name %>/<%= controller.action_name %>">
  <%= csrf_meta_tags %>
  <%= guardian_token_tags %>

<div class="pure-menu pure-menu-horizontal">
    <span class="pure-menu-heading">Pusher Clone Demo</span>

    <ul class="pure-menu-list">
    </ul>
</div>

<div class="pure-g-r">
  <div class="pure-u-1-3 message-form">
    <div class="form-header">Broadcast your message remotely</div>
    <%= yield %>
  </div>
  
  <div class="pure-u-1-3 message-receiver">
    <ul class="events">
      
    </ul>
  </div>
</div>


</body>
</html>